# Cirrus CI - Showcase: Build stremio-server on ARM64
#
# This is a simplified example showing Cirrus CI ARM64 native builds.
# stremio-server is a pure Node.js application (no compilation needed)
# so it builds quickly without QEMU complexity.
#
# For production builds of all packages, see GitHub Actions which uses
# native ARM64 runners (ubuntu-24.04-arm) with bubblewrap for fast builds.

task:
  name: Build stremio-server (ARM64 showcase)
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'main'

  # ARM64 native on AWS Graviton2 - lightweight resources for simple builds
  arm_container:
    image: alpine:latest
    cpu: 2
    memory: 4G

  env:
    ARCH: aarch64
    MELANGE_VERSION: latest
    APK_SIGNING_KEY: ENCRYPTED[!1ef534804032cc4990b3feb5c4dbe292a23b5003dbfacd059aa9ca3ea63a950eb975838ae6e1305303df4217c8caf97c!]

  # Install dependencies
  install_deps_script:
    - apk add --no-cache curl git bash wget tar gzip jq openssl

  # Install Melange
  install_melange_script:
    - |
      ACTUAL_VERSION=$(curl -s https://api.github.com/repos/chainguard-dev/melange/releases/latest | jq -r '.tag_name')
      echo "Installing Melange $ACTUAL_VERSION for ARM64"
      wget -q https://github.com/chainguard-dev/melange/releases/download/${ACTUAL_VERSION}/melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz
      tar -xzf melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz
      find . -name "melange" -type f -exec mv {} /usr/local/bin/ \;
      chmod +x /usr/local/bin/melange
      melange version
      rm -f melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz

  # Setup signing keys
  setup_keys_script:
    - |
      printf '%s\n' "$APK_SIGNING_KEY" > melange-pkcs8.rsa
      openssl rsa -in melange-pkcs8.rsa -out melange.rsa -traditional
      openssl rsa -in melange.rsa -pubout > melange.rsa.pub
      rm melange-pkcs8.rsa
      wget -q -O wolfi-signing.rsa.pub https://packages.wolfi.dev/os/wolfi-signing.rsa.pub

  # Build stremio-server (Node.js package, no compilation needed)
  build_script:
    - mkdir -p build-output/aarch64
    - |
      melange build \
        --arch aarch64 \
        --signing-key melange.rsa \
        --keyring-append melange.rsa.pub \
        --keyring-append wolfi-signing.rsa.pub \
        --repository-append https://packages.wolfi.dev/os \
        --pipeline-dir pipelines \
        --out-dir build-output/aarch64 \
        packages/stremio-server.yaml
    - ls -lh build-output/aarch64/

  # Upload artifacts
  always:
    apk_packages_artifacts:
      path: "build-output/aarch64/*.apk"
