# Cirrus CI - Showcase: Build stremio-server on ARM64
#
# This is a simplified example showing Cirrus CI ARM64 native builds.
# stremio-server is a pure Node.js application (no compilation needed)
# so it builds quickly without QEMU complexity.
#
# For production builds of all packages, see GitHub Actions which uses
# native ARM64 runners (ubuntu-24.04-arm) with bubblewrap for fast builds.

task:
  name: Build stremio-server (ARM64 showcase)
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'main'

  # ARM64 native on AWS Graviton2 - lightweight resources for simple builds
  arm_container:
    image: alpine:latest
    cpu: 2
    memory: 4G

  env:
    ARCH: aarch64
    MELANGE_VERSION: latest
    APK_SIGNING_KEY: ENCRYPTED[!1ef534804032cc4990b3feb5c4dbe292a23b5003dbfacd059aa9ca3ea63a950eb975838ae6e1305303df4217c8caf97c!]

  # Install dependencies (including QEMU for emulation)
  install_deps_script:
    - apk add --no-cache curl git bash qemu-system-aarch64 linux-virt wget tar gzip jq openssl cpio file
    - |
      # Check if virtio modules are available in the installed system
      echo "Checking for virtio modules in installed system..."
      if [ -d "/lib/modules" ]; then
        echo "  System modules directory exists:"
        ls -la /lib/modules/ 2>/dev/null | head -5
        KERNEL_VER=$(ls /lib/modules/ 2>/dev/null | head -1)
        if [ -n "$KERNEL_VER" ]; then
          echo "  Found kernel version: $KERNEL_VER"
          echo "  Searching for virtio modules:"
          find /lib/modules/$KERNEL_VER -name "*virtio*" -type f 2>/dev/null | head -10 || echo "    No virtio modules found in system"
        fi
      fi

  # Install Melange
  install_melange_script:
    - |
      ACTUAL_VERSION=$(curl -s https://api.github.com/repos/chainguard-dev/melange/releases/latest | jq -r '.tag_name')
      echo "Installing Melange $ACTUAL_VERSION for ARM64"
      wget -q https://github.com/chainguard-dev/melange/releases/download/${ACTUAL_VERSION}/melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz
      tar -xzf melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz
      find . -name "melange" -type f -exec mv {} /usr/local/bin/ \;
      chmod +x /usr/local/bin/melange
      melange version
      rm -f melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz

  # Create QEMU wrapper to force TCG instead of KVM (KVM not available in container)
  setup_qemu_wrapper_script:
    - |
      # Move real QEMU binary
      mv /usr/bin/qemu-system-aarch64 /usr/bin/qemu-system-aarch64.real

      # Create wrapper script that:
      # 1. Replaces -accel kvm with -accel tcg,thread=multi
      # 2. Fixes memory, machine, and CPU settings for TCG
      # 3. COMBINES initramfs files (Alpine's virtio modules + melange's initramfs)
      cat > /usr/bin/qemu-system-aarch64 << 'EOF'
      #!/bin/sh
      # QEMU wrapper to force TCG acceleration and inject virtio modules
      # KVM is not available in Cirrus CI ARM containers

      # Debug logging
      echo "=== QEMU wrapper invoked at $(date) ===" >> /tmp/qemu-debug.log
      echo "Original arguments:" >> /tmp/qemu-debug.log
      for arg in "$@"; do
        echo "  '$arg'" >> /tmp/qemu-debug.log
      done

      # Process arguments to replace problematic values
      # - Replace -accel kvm with -accel tcg,thread=multi (KVM not available)
      # - Replace -m <value> with -m 16G (cap memory)
      # - Replace -machine <value> with -machine virt (ensure 64-bit addressing)
      # - Replace -cpu host with -cpu max (TCG needs explicit CPU)
      # - INTERCEPT -initrd and concatenate with Alpine's initramfs (for virtio modules)
      new_args=""
      prev_arg=""
      skip_next=false
      skip_reason=""
      melange_initrd=""

      for arg in "$@"; do
        # If we're processing the -initrd value (melange_initrd is PENDING)
        if [ "$melange_initrd" = "PENDING" ]; then
          echo "  Melange's initrd path: '$arg'" >> /tmp/qemu-debug.log

          # Create combined initramfs: Alpine's (virtio modules) + melange's (build env)
          # Linux kernel merges concatenated UNCOMPRESSED cpio archives
          COMBINED_INITRD="/tmp/combined-initramfs-$$.cpio.gz"
          echo "  Creating combined initramfs: $COMBINED_INITRD" >> /tmp/qemu-debug.log

          if [ -f "/boot/initramfs-virt" ]; then
            echo "  Step 1: Decompress Alpine's initramfs" >> /tmp/qemu-debug.log
            gunzip -c /boot/initramfs-virt > /tmp/alpine-$$.cpio 2>> /tmp/qemu-debug.log

            echo "  Step 2: Decompress melange's initramfs" >> /tmp/qemu-debug.log
            gunzip -c "$arg" > /tmp/melange-$$.cpio 2>> /tmp/qemu-debug.log

            echo "  Step 3: Concatenate uncompressed cpio archives" >> /tmp/qemu-debug.log
            cat /tmp/alpine-$$.cpio /tmp/melange-$$.cpio > /tmp/combined-$$.cpio 2>> /tmp/qemu-debug.log

            echo "  Step 4: Re-compress combined initramfs" >> /tmp/qemu-debug.log
            gzip -c /tmp/combined-$$.cpio > "$COMBINED_INITRD" 2>> /tmp/qemu-debug.log

            if [ -f "$COMBINED_INITRD" ]; then
              COMBINED_SIZE=$(stat -c%s "$COMBINED_INITRD")
              echo "  ✓ Combined initramfs created: $COMBINED_SIZE bytes" >> /tmp/qemu-debug.log

              # Cleanup temp files
              rm -f /tmp/alpine-$$.cpio /tmp/melange-$$.cpio /tmp/combined-$$.cpio

              # Add the -initrd argument with combined path
              escaped_arg=$(printf '%s' "-initrd" | sed "s/'/'\\\\''/g")
              escaped_path=$(printf '%s' "$COMBINED_INITRD" | sed "s/'/'\\\\''/g")
              new_args="$new_args '$escaped_arg' '$escaped_path'"
              melange_initrd="$COMBINED_INITRD"
            else
              echo "  ✗ ERROR: Failed to create combined initramfs, using melange's only" >> /tmp/qemu-debug.log
              rm -f /tmp/alpine-$$.cpio /tmp/melange-$$.cpio /tmp/combined-$$.cpio
              escaped_arg=$(printf '%s' "-initrd" | sed "s/'/'\\\\''/g")
              escaped_path=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
              new_args="$new_args '$escaped_arg' '$escaped_path'"
              melange_initrd=""
            fi
          else
            echo "  ✗ WARNING: /boot/initramfs-virt not found, using melange's initrd only" >> /tmp/qemu-debug.log
            escaped_arg=$(printf '%s' "-initrd" | sed "s/'/'\\\\''/g")
            escaped_path=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
            new_args="$new_args '$escaped_arg' '$escaped_path'"
            melange_initrd=""
          fi
          # Continue to next argument
          prev_arg="$arg"
          continue
        fi

        # Skip this iteration if previous arg was -m, -machine, or -cpu (we already added replacement)
        if [ "$skip_next" = true ]; then
          skip_next=false
          echo "Replaced $skip_reason value '$arg' with replacement" >> /tmp/qemu-debug.log
          prev_arg=""
          skip_reason=""
          continue
        fi

        # Replace -accel kvm with -accel tcg,thread=multi
        if [ "$prev_arg" = "-accel" ] && [ "$arg" = "kvm" ]; then
          echo "Replaced -accel kvm with -accel tcg,thread=multi" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "tcg,thread=multi" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped'"
        # If current arg is -m, add it and mark to skip next value (replace with 16G)
        elif [ "$arg" = "-m" ]; then
          echo "Found -m argument, will replace value with 16G" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped' '16G'"
          skip_next=true
          skip_reason="-m"
        # If current arg is -machine, add it and mark to skip next value (replace with virt)
        elif [ "$arg" = "-machine" ]; then
          echo "Found -machine argument, will replace value with virt" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped' 'virt'"
          skip_next=true
          skip_reason="-machine"
        # If current arg is -cpu, add it and mark to skip next value (replace with max)
        elif [ "$arg" = "-cpu" ]; then
          echo "Found -cpu argument, will replace value with max (TCG needs explicit CPU)" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped' 'max'"
          skip_next=true
          skip_reason="-cpu"
        # CRITICAL: If current arg is -initrd, mark that next arg is the initrd path
        elif [ "$arg" = "-initrd" ]; then
          echo "Found -initrd argument, will concatenate with Alpine initramfs" >> /tmp/qemu-debug.log
          # Mark that next argument is the initrd path to process
          melange_initrd="PENDING"
        else
          # Regular argument - properly quote and add
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped'"
        fi

        prev_arg="$arg"
      done

      echo "Final command: /usr/bin/qemu-system-aarch64.real $new_args" >> /tmp/qemu-debug.log

      # Execute with eval to properly handle quoted arguments
      eval exec /usr/bin/qemu-system-aarch64.real $new_args
      EOF

      chmod +x /usr/bin/qemu-system-aarch64
      echo "QEMU wrapper installed - will use TCG instead of KVM"

  # Setup kernel path for melange
  setup_kernel_script:
    - |
      echo "=========================================="
      echo "SETUP KERNEL SCRIPT"
      echo "=========================================="

      # QEMU runner requires kernel and initramfs from linux-virt package
      KERNEL_PATH="/boot/vmlinuz-virt"
      INITRAMFS_PATH="/boot/initramfs-virt"

      echo "Verifying kernel and initramfs..."

      if [ ! -f "$KERNEL_PATH" ]; then
        echo "ERROR: Kernel not found at $KERNEL_PATH"
        ls -lh /boot/
        exit 1
      fi

      if [ ! -f "$INITRAMFS_PATH" ]; then
        echo "ERROR: Initramfs not found at $INITRAMFS_PATH"
        ls -lh /boot/
        exit 1
      fi

      KERNEL_SIZE=$(stat -c%s $KERNEL_PATH)
      INITRAMFS_SIZE=$(stat -c%s $INITRAMFS_PATH)
      echo "✓ Kernel: $KERNEL_PATH ($KERNEL_SIZE bytes)"
      echo "✓ Initramfs: $INITRAMFS_PATH ($INITRAMFS_SIZE bytes)"
      echo ""
      echo "The QEMU wrapper will automatically combine:"
      echo "  1. Alpine's initramfs (virtio modules + base system)"
      echo "  2. Melange's initramfs (build environment)"
      echo ""

      # Set kernel path for melange
      echo "export QEMU_KERNEL_IMAGE=$KERNEL_PATH" >> $CIRRUS_ENV
      echo "✓ QEMU_KERNEL_IMAGE exported for melange"

  # Setup signing keys
  setup_keys_script:
    - |
      printf '%s\n' "$APK_SIGNING_KEY" > melange-pkcs8.rsa
      openssl rsa -in melange-pkcs8.rsa -out melange.rsa -traditional
      openssl rsa -in melange.rsa -pubout > melange.rsa.pub
      rm melange-pkcs8.rsa
      wget -q -O wolfi-signing.rsa.pub https://packages.wolfi.dev/os/wolfi-signing.rsa.pub

  # Build stremio-server (Node.js package, simple showcase build)
  build_script:
    - mkdir -p build-output/aarch64 build-output/logs
    - |
      # Source environment variables from CIRRUS_ENV
      if [ -f "$CIRRUS_ENV" ]; then
        echo "Loading environment variables from $CIRRUS_ENV:"
        cat "$CIRRUS_ENV"
        set -a
        source "$CIRRUS_ENV"
        set +a
      fi

      # Set default kernel image if not already set
      export QEMU_KERNEL_IMAGE=${QEMU_KERNEL_IMAGE:-/boot/vmlinuz-virt}

      echo "=========================================="
      echo "BUILD ENVIRONMENT"
      echo "=========================================="
      echo "QEMU_KERNEL_IMAGE: $QEMU_KERNEL_IMAGE"
      echo "Architecture: aarch64"
      echo "Package: stremio-server"
      echo ""
      echo "Note: QEMU wrapper will automatically combine initramfs files"
      echo "      to inject virtio modules from Alpine into melange's VM"
      echo ""

      # Build stremio-server
      melange build \
        --runner qemu \
        --arch aarch64 \
        --signing-key melange.rsa \
        --keyring-append melange.rsa.pub \
        --keyring-append wolfi-signing.rsa.pub \
        --repository-append https://packages.wolfi.dev/os \
        --pipeline-dir pipelines \
        --out-dir build-output/aarch64 \
        packages/stremio-server.yaml 2>&1 | tee /tmp/melange-build.log

    - echo "=== Build output ==="
    - ls -lh build-output/aarch64/ || true
    - echo ""
    - echo "=== Copying QEMU debug log to artifacts ==="
    - cp /tmp/qemu-debug.log build-output/logs/ 2>/dev/null || echo "No QEMU debug log found"

  # Upload artifacts
  always:
    apk_packages_artifacts:
      path: "build-output/aarch64/*.apk"
    qemu_logs_artifacts:
      path: "build-output/logs/qemu-debug.log"
