# ============================================================================
# CIRRUS CI CONFIGURATION - Docker Builder with ARM64
# ============================================================================
#
# Uses Cirrus CI's Docker Builder on Google Compute Engine ARM64 VMs
# This provides PRIVILEGED container support, allowing melange to work properly
#
# Key differences from previous approach:
# - Uses docker_builder instead of arm_container
# - Runs melange in privileged Docker container (no QEMU wrapper needed)
# - Can use bubblewrap runner (native, fast)
# - No initramfs combination hacks required
#
# Resources: 4 CPUs, 16GB RAM (Google Compute Engine ARM64 VM)
# ============================================================================

task:
  name: Build stremio-server (ARM64 with privileged Docker)
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'main'

  # Use Docker Builder with ARM64 (runs on GCE ARM64 VMs)
  docker_builder:
    env:
      CIRRUS_ARCH: arm64

  env:
    ARCH: aarch64
    MELANGE_VERSION: latest
    APK_SIGNING_KEY: ENCRYPTED[!1ef534804032cc4990b3feb5c4dbe292a23b5003dbfacd059aa9ca3ea63a950eb975838ae6e1305303df4217c8caf97c!]

  # Generate signing keys
  setup_keys_script:
    - |
      # Use encrypted production key if building on master/main
      if [ "$CIRRUS_BRANCH" = "master" ] || [ "$CIRRUS_BRANCH" = "main" ]; then
        echo "Using encrypted APK signing key for production builds"
        echo "$APK_SIGNING_KEY" | base64 -d > melange.rsa
        chmod 600 melange.rsa

        # Generate public key from private key
        openssl rsa -in melange.rsa -pubout > melange.rsa.pub 2>/dev/null
      else
        echo "Generating ephemeral signing keys for branch builds"
        docker run --rm -v "$PWD:/work" cgr.dev/chainguard/melange:latest keygen /work/melange.rsa
      fi

      # Download official Wolfi signing key for dependency resolution
      wget -q https://packages.wolfi.dev/os/wolfi-signing.rsa.pub -O wolfi-signing.rsa.pub

      echo "✓ Signing keys ready"
      ls -lh melange.rsa* wolfi-signing.rsa.pub

  # Build stremio-server with privileged melange container
  build_script:
    - |
      mkdir -p build-output/aarch64

      echo "Building stremio-server for ARM64 using privileged Docker container..."
      docker run --rm --privileged \
        -v "$PWD:/work" \
        -w /work \
        cgr.dev/chainguard/melange:latest \
        build \
        --arch aarch64 \
        --signing-key melange.rsa \
        --keyring-append melange.rsa.pub \
        --keyring-append wolfi-signing.rsa.pub \
        --repository-append https://packages.wolfi.dev/os \
        --pipeline-dir pipelines \
        --out-dir build-output/aarch64 \
        packages/stremio-server.yaml

      echo ""
      echo "=== Build output ==="
      ls -lh build-output/aarch64/

  # Download existing packages from SourceForge to include in APKINDEX
  download_existing_packages_script:
    - |
      echo "=== Downloading existing aarch64 packages from SourceForge ==="
      echo "This ensures APKINDEX includes ALL packages, not just newly built ones"

      # Install lftp for downloading
      apt-get update && apt-get install -y lftp

      mkdir -p existing-packages/aarch64

      # Download existing packages using lftp (public HTTP, no auth needed)
      lftp -c "
        set ssl:verify-certificate no
        set net:timeout 60
        set net:max-retries 3
        open https://downloads.sourceforge.net/project/wolfi/
        mirror --verbose --exclude-glob 'APKINDEX*' aarch64/ existing-packages/aarch64/
      " || echo "No existing packages found (first publish?)"

      PKG_COUNT=$(find existing-packages/aarch64 -name "*.apk" 2>/dev/null | wc -l)
      echo "Downloaded $PKG_COUNT existing packages from SourceForge"

  # Merge new and existing packages, then generate APKINDEX
  generate_apkindex_script:
    - |
      echo "=== Merging packages and generating APKINDEX ==="

      mkdir -p final-output/aarch64

      # Copy existing packages first
      if [ -d "existing-packages/aarch64" ]; then
        cp existing-packages/aarch64/*.apk final-output/aarch64/ 2>/dev/null || true
      fi

      # Copy newly built packages (overwrites if same name/version)
      cp build-output/aarch64/*.apk final-output/aarch64/ 2>/dev/null || true

      TOTAL_PKGS=$(ls final-output/aarch64/*.apk 2>/dev/null | wc -l)
      echo "Total packages to include in APKINDEX: $TOTAL_PKGS"

      if [ "$TOTAL_PKGS" -gt 0 ]; then
        # Copy signing key into directory for Docker access
        cp melange.rsa final-output/aarch64/

        cd final-output/aarch64

        # Generate and sign APKINDEX using Alpine container
        docker run --rm \
          -v $PWD:/work \
          -w /work \
          alpine:latest \
          sh -c "apk add --no-cache apk-tools abuild && \
            apk index --allow-untrusted -o APKINDEX.tar.gz *.apk && \
            abuild-sign -k /work/melange.rsa APKINDEX.tar.gz && \
            ls -lh APKINDEX.tar.gz"

        # Remove signing key from output directory (security)
        rm melange.rsa

        cd ../..

        echo "APKINDEX generated and signed successfully"
        ls -lh final-output/aarch64/APKINDEX.tar.gz
      else
        echo "ERROR: No packages found to index!"
        exit 1
      fi

  # Upload build artifacts
  apk_packages_artifacts:
    path: "final-output/aarch64/*.apk"

  apkindex_artifacts:
    path: "final-output/aarch64/APKINDEX.tar.gz"
