# Cirrus CI - Showcase: Build stremio-server on ARM64
#
# This is a simplified example showing Cirrus CI ARM64 native builds.
# stremio-server is a pure Node.js application (no compilation needed)
# so it builds quickly without QEMU complexity.
#
# For production builds of all packages, see GitHub Actions which uses
# native ARM64 runners (ubuntu-24.04-arm) with bubblewrap for fast builds.

task:
  name: Build stremio-server (ARM64 showcase)
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'main'

  # ARM64 native on AWS Graviton2 - lightweight resources for simple builds
  arm_container:
    image: alpine:latest
    cpu: 2
    memory: 4G

  env:
    ARCH: aarch64
    MELANGE_VERSION: latest
    APK_SIGNING_KEY: ENCRYPTED[!1ef534804032cc4990b3feb5c4dbe292a23b5003dbfacd059aa9ca3ea63a950eb975838ae6e1305303df4217c8caf97c!]

  # Install dependencies (including QEMU for emulation)
  install_deps_script:
    - apk add --no-cache curl git bash qemu-system-aarch64 linux-virt wget tar gzip jq openssl cpio file

  # Install Melange
  install_melange_script:
    - |
      ACTUAL_VERSION=$(curl -s https://api.github.com/repos/chainguard-dev/melange/releases/latest | jq -r '.tag_name')
      echo "Installing Melange $ACTUAL_VERSION for ARM64"
      wget -q https://github.com/chainguard-dev/melange/releases/download/${ACTUAL_VERSION}/melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz
      tar -xzf melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz
      find . -name "melange" -type f -exec mv {} /usr/local/bin/ \;
      chmod +x /usr/local/bin/melange
      melange version
      rm -f melange_${ACTUAL_VERSION#v}_linux_arm64.tar.gz

  # Create QEMU wrapper to force TCG instead of KVM (KVM not available in container)
  setup_qemu_wrapper_script:
    - |
      # Move real QEMU binary
      mv /usr/bin/qemu-system-aarch64 /usr/bin/qemu-system-aarch64.real

      # Create wrapper script that replaces -accel kvm with -accel tcg,thread=multi
      cat > /usr/bin/qemu-system-aarch64 << 'EOF'
      #!/bin/sh
      # QEMU wrapper to force TCG acceleration instead of KVM
      # Also adds machine type and memory limit to fix addressing issues
      # KVM is not available in Cirrus CI ARM containers

      # Debug logging
      echo "=== QEMU wrapper invoked at $(date) ===" >> /tmp/qemu-debug.log
      echo "Original arguments:" >> /tmp/qemu-debug.log
      for arg in "$@"; do
        echo "  '$arg'" >> /tmp/qemu-debug.log
      done

      # Process arguments to replace problematic values
      # - Replace -accel kvm with -accel tcg,thread=multi (KVM not available)
      # - Replace -m <value> with -m 16G (cap memory, Melange calculates wrong value)
      # - Replace -machine <value> with -machine virt (ensure 64-bit addressing)
      # - Replace -cpu host with -cpu max (TCG needs explicit CPU, not host)
      # - Combine -initrd <melange-initrd> with /boot/initramfs-virt (for virtio modules)
      new_args=""
      prev_arg=""
      skip_next=false
      skip_reason=""
      melange_initrd=""

      for arg in "$@"; do
        # Skip this iteration if previous arg was -m, -machine, -cpu, or -initrd (we already added our replacement)
        if [ "$skip_next" = true ]; then
          # If we're skipping because of -initrd, save this arg as the melange initrd path
          if [ "$skip_reason" = "-initrd" ]; then
            melange_initrd="$arg"
            echo "Melange initrd path: $melange_initrd" >> /tmp/qemu-debug.log
          fi
          skip_next=false
          echo "Replaced $skip_reason value '$arg' with replacement" >> /tmp/qemu-debug.log
          # Reset prev_arg so next iteration doesn't use this value
          prev_arg=""
          skip_reason=""
          continue
        fi

        # Replace -accel kvm with -accel tcg,thread=multi
        if [ "$prev_arg" = "-accel" ] && [ "$arg" = "kvm" ]; then
          echo "Replaced -accel kvm with -accel tcg,thread=multi" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "tcg,thread=multi" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped'"
        # If current arg is -m, add it and mark to skip next value (replace with 16G)
        elif [ "$arg" = "-m" ]; then
          echo "Found -m argument, will replace value with 16G" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped' '16G'"
          skip_next=true
          skip_reason="-m"
        # If current arg is -machine, add it and mark to skip next value (replace with virt)
        elif [ "$arg" = "-machine" ]; then
          echo "Found -machine argument, will replace value with virt" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped' 'virt'"
          skip_next=true
          skip_reason="-machine"
        # If current arg is -cpu, add it and mark to skip next value (replace with max)
        elif [ "$arg" = "-cpu" ]; then
          echo "Found -cpu argument, will replace value with max (TCG needs explicit CPU)" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped' 'max'"
          skip_next=true
          skip_reason="-cpu"
        # If current arg is -initrd, mark to skip next value (we'll save it as melange_initrd)
        elif [ "$arg" = "-initrd" ]; then
          echo "Found -initrd argument from melange" >> /tmp/qemu-debug.log
          # Don't add -initrd yet, we'll add the combined version later
          skip_next=true
          skip_reason="-initrd"
        else
          # Properly quote and add all other arguments
          escaped=$(printf '%s' "$arg" | sed "s/'/'\\\\''/g")
          new_args="$new_args '$escaped'"
        fi

        prev_arg="$arg"
      done

      # Combine melange's initramfs with Alpine's initramfs (which has virtio modules)
      # Linux kernel supports multiple initramfs cpio archives concatenated together
      if [ -n "$melange_initrd" ] && [ -f "$melange_initrd" ]; then
        echo "Combining initramfs files..." >> /tmp/qemu-debug.log
        echo "  Melange initrd: $melange_initrd" >> /tmp/qemu-debug.log
        echo "  Alpine initrd: /boot/initramfs-virt (contains virtio modules)" >> /tmp/qemu-debug.log

        # Verify Alpine's initramfs exists
        if [ ! -f "/boot/initramfs-virt" ]; then
          echo "ERROR: Alpine initramfs not found at /boot/initramfs-virt" >> /tmp/qemu-debug.log
          echo "ERROR: Using melange's initrd only (virtio modules may be missing)" >> /tmp/qemu-debug.log
          escaped=$(printf '%s' "$melange_initrd" | sed "s/'/'\\\\''/g")
          new_args="$new_args '-initrd' '$escaped'"
        else
          # Combine initramfs files properly:
          # 1. Extract both cpio archives (they may be gzip compressed)
          # 2. Concatenate the extracted cpio files
          # 3. Compress the result with gzip
          echo "Extracting and combining initramfs files..." >> /tmp/qemu-debug.log
          
          COMBINE_FAILED=false
          
          # Extract Alpine's initramfs (handle both compressed and uncompressed)
          if file /boot/initramfs-virt | grep -q gzip; then
            echo "  Alpine initramfs is gzip compressed, extracting..." >> /tmp/qemu-debug.log
            if ! gunzip -c /boot/initramfs-virt > /tmp/alpine-initramfs.cpio 2>> /tmp/qemu-debug.log; then
              echo "ERROR: Failed to extract Alpine initramfs" >> /tmp/qemu-debug.log
              COMBINE_FAILED=true
            fi
          else
            echo "  Alpine initramfs is uncompressed, copying..." >> /tmp/qemu-debug.log
            if ! cp /boot/initramfs-virt /tmp/alpine-initramfs.cpio 2>> /tmp/qemu-debug.log; then
              echo "ERROR: Failed to copy Alpine initramfs" >> /tmp/qemu-debug.log
              COMBINE_FAILED=true
            fi
          fi
          
          # Extract melange's initramfs (handle both compressed and uncompressed)
          if [ "$COMBINE_FAILED" = false ]; then
            if file "$melange_initrd" | grep -q gzip; then
              echo "  Melange initramfs is gzip compressed, extracting..." >> /tmp/qemu-debug.log
              if ! gunzip -c "$melange_initrd" > /tmp/melange-initramfs.cpio 2>> /tmp/qemu-debug.log; then
                echo "ERROR: Failed to extract melange initramfs" >> /tmp/qemu-debug.log
                COMBINE_FAILED=true
              fi
            else
              echo "  Melange initramfs is uncompressed, copying..." >> /tmp/qemu-debug.log
              if ! cp "$melange_initrd" /tmp/melange-initramfs.cpio 2>> /tmp/qemu-debug.log; then
                echo "ERROR: Failed to copy melange initramfs" >> /tmp/qemu-debug.log
                COMBINE_FAILED=true
              fi
            fi
          fi
          
          # Concatenate the cpio files (Linux kernel supports multiple cpio archives)
          # Order matters: files from later archives override files from earlier ones
          # Put melange first (init scripts + build environment), then Alpine (binaries + virtio modules override)
          # This ensures melange's init scripts run, and Alpine's essential binaries (mount, etc.) are available
          if [ "$COMBINE_FAILED" = false ]; then
            if cat /tmp/melange-initramfs.cpio /tmp/alpine-initramfs.cpio > /tmp/combined-initramfs.cpio 2>> /tmp/qemu-debug.log; then
              # Compress the combined cpio with gzip
              if gzip -c /tmp/combined-initramfs.cpio > /tmp/combined-initramfs 2>> /tmp/qemu-debug.log; then
                if [ -f /tmp/combined-initramfs ] && [ -s /tmp/combined-initramfs ]; then
                  COMBINED_SIZE=$(stat -c%s /tmp/combined-initramfs 2>/dev/null || echo "unknown")
                  ALPINE_SIZE=$(stat -c%s /tmp/alpine-initramfs.cpio 2>/dev/null || echo "unknown")
                  MELANGE_SIZE=$(stat -c%s /tmp/melange-initramfs.cpio 2>/dev/null || echo "unknown")
                  echo "Combined initramfs created successfully:" >> /tmp/qemu-debug.log
                  echo "  Alpine cpio: $ALPINE_SIZE bytes (first - virtio modules)" >> /tmp/qemu-debug.log
                  echo "  Melange cpio: $MELANGE_SIZE bytes (second - init scripts override Alpine's)" >> /tmp/qemu-debug.log
                  echo "  Combined (gzipped): $COMBINED_SIZE bytes" >> /tmp/qemu-debug.log
                  echo "  Order: Alpine first, then melange (melange init scripts override Alpine's)" >> /tmp/qemu-debug.log
                  new_args="$new_args '-initrd' '/tmp/combined-initramfs'"
                else
                  echo "ERROR: Combined initramfs file is empty after compression" >> /tmp/qemu-debug.log
                  COMBINE_FAILED=true
                fi
              else
                echo "ERROR: Failed to compress combined initramfs" >> /tmp/qemu-debug.log
                COMBINE_FAILED=true
              fi
              # Cleanup temporary files
              rm -f /tmp/alpine-initramfs.cpio /tmp/melange-initramfs.cpio /tmp/combined-initramfs.cpio
            else
              echo "ERROR: Failed to concatenate cpio files" >> /tmp/qemu-debug.log
              COMBINE_FAILED=true
            fi
          fi
          
          # Fallback to melange's initrd only if combination failed
          if [ "$COMBINE_FAILED" = true ]; then
            echo "Falling back to melange's initrd only" >> /tmp/qemu-debug.log
            escaped=$(printf '%s' "$melange_initrd" | sed "s/'/'\\\\''/g")
            new_args="$new_args '-initrd' '$escaped'"
            rm -f /tmp/alpine-initramfs.cpio /tmp/melange-initramfs.cpio /tmp/combined-initramfs.cpio /tmp/combined-initramfs
          fi
        fi
      elif [ -n "$melange_initrd" ]; then
        echo "WARNING: Melange initrd path specified but file not found: $melange_initrd" >> /tmp/qemu-debug.log
        echo "WARNING: Using Alpine's initramfs only" >> /tmp/qemu-debug.log
        if [ -f "/boot/initramfs-virt" ]; then
          new_args="$new_args '-initrd' '/boot/initramfs-virt'"
        else
          echo "ERROR: Alpine initramfs also not found, QEMU may fail to boot" >> /tmp/qemu-debug.log
        fi
      else
        echo "No melange initrd found, using only Alpine's initramfs" >> /tmp/qemu-debug.log
        if [ -f "/boot/initramfs-virt" ]; then
          new_args="$new_args '-initrd' '/boot/initramfs-virt'"
        else
          echo "ERROR: Alpine initramfs not found at /boot/initramfs-virt" >> /tmp/qemu-debug.log
        fi
      fi

      echo "Final command: /usr/bin/qemu-system-aarch64.real $new_args" >> /tmp/qemu-debug.log

      # Execute with eval to properly handle quoted arguments
      eval exec /usr/bin/qemu-system-aarch64.real $new_args
      EOF

      chmod +x /usr/bin/qemu-system-aarch64
      echo "QEMU wrapper installed - will use TCG instead of KVM"

  # Setup kernel for QEMU runner (QEMU needs kernel and initramfs to boot VM)
  setup_kernel_script:
    - |
      # QEMU runner requires kernel and initramfs from linux-virt package
      # Initramfs contains virtio modules needed for QEMU storage/network
      KERNEL_PATH="/boot/vmlinuz-virt"
      INITRAMFS_PATH="/boot/initramfs-virt"
      if [ ! -f "$KERNEL_PATH" ]; then
        echo "ERROR: Kernel not found at $KERNEL_PATH"
        ls -lh /boot/
        exit 1
      fi
      if [ ! -f "$INITRAMFS_PATH" ]; then
        echo "ERROR: Initramfs not found at $INITRAMFS_PATH"
        ls -lh /boot/
        exit 1
      fi
      echo "Kernel available at: $KERNEL_PATH"
      echo "Initramfs available at: $INITRAMFS_PATH"
      echo "export QEMU_KERNEL_IMAGE=$KERNEL_PATH" >> $CIRRUS_ENV
      echo "export QEMU_INITRAMFS=$INITRAMFS_PATH" >> $CIRRUS_ENV

  # Setup signing keys
  setup_keys_script:
    - |
      printf '%s\n' "$APK_SIGNING_KEY" > melange-pkcs8.rsa
      openssl rsa -in melange-pkcs8.rsa -out melange.rsa -traditional
      openssl rsa -in melange.rsa -pubout > melange.rsa.pub
      rm melange-pkcs8.rsa
      wget -q -O wolfi-signing.rsa.pub https://packages.wolfi.dev/os/wolfi-signing.rsa.pub

  # Build stremio-server (Node.js package, no compilation needed)
  build_script:
    - mkdir -p build-output/aarch64 build-output/logs
    - |
      export QEMU_KERNEL_IMAGE=/boot/vmlinuz-virt
      export QEMU_INITRAMFS=/boot/initramfs-virt
      melange build \
        --runner qemu \
        --arch aarch64 \
        --signing-key melange.rsa \
        --keyring-append melange.rsa.pub \
        --keyring-append wolfi-signing.rsa.pub \
        --repository-append https://packages.wolfi.dev/os \
        --pipeline-dir pipelines \
        --out-dir build-output/aarch64 \
        packages/stremio-server.yaml || true
    - ls -lh build-output/aarch64/ || true
    - cp /tmp/qemu-debug.log build-output/logs/ || echo "No QEMU debug log found"

  # Upload artifacts
  always:
    apk_packages_artifacts:
      path: "build-output/aarch64/*.apk"
    qemu_logs_artifacts:
      path: "build-output/logs/qemu-debug.log"
