package:
  name: libvpx
  version: 1.15.2
  epoch: 0
  description: Library for the vp8/vp9 codecs
  copyright:
  - license: BSD-3-Clause
environment:
  contents:
    packages:
    - bash
    - build-base
    - busybox
    - ca-certificates-bundle
    - coreutils
    - diffutils
    - linux-headers
    - nasm
    - perl
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
pipeline:
- uses: fetch
  with:
    expected-sha512: 824fe8719e4115ec359ae0642f5e1cea051d458f09eb8c24d60858cf082f66e411215e23228173ab154044bafbdfbb2d93b589bb726f55b233939b91f928aae0
    uri: https://github.com/webmproject/libvpx/archive/v${{package.version}}/libvpx-v${{package.version}}.tar.gz
- uses: patch
  with:
    patches: libvpx/fix-arm-float-abi.patch
- runs: "# build fix for arm\nexport CROSS=\" \"\nexport CFLAGS=\"$CFLAGS -O2 -flto=auto\
    \ -ffat-lto-objects\"\nexport CXXFLAGS=\"$CXXFLAGS -O2 -flto=auto -ffat-lto-objects\"\
    \n\n./configure \\\n  --prefix=/usr \\\n  --disable-install-srcs \\\n  --disable-static\
    \ \\\n  --enable-libs \\\n  --enable-multithread \\\n  --enable-pic \\\n  --enable-postproc\
    \ \\\n  --enable-runtime-cpu-detect \\\n  --enable-shared \\\n  --enable-temporal-denoising\
    \ \\\n  --enable-unit-tests \\\n  --enable-vp8 \\\n  --enable-vp9 \\\n  --enable-vp9-highbitdepth\
    \ \\\n  --enable-vp9-postproc \\\n  --enable-vp9-temporal-denoising\n"
- uses: autoconf/make
- uses: autoconf/make-install
- uses: strip
subpackages:
- name: libvpx-dev
  pipeline:
  - uses: split/dev
  dependencies:
    runtime:
    - libvpx
  description: libvpx dev
  test:
    pipeline:
    - uses: test/pkgconf
    - uses: test/tw/ldd-check
- name: libvpx-utils
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/bin

      mv ${{targets.destdir}}/usr/bin/* ${{targets.subpkgdir}}/usr/bin/

      '
  description: libvpx (tools)
update:
  enabled: true
  github:
    identifier: webmproject/libvpx
    strip-prefix: v
    use-tag: true
test:
  pipeline:
  - name: Verify shared library exists
    runs: 'test -f /usr/lib/libvpx.so

      '
  - name: Test vpxenc tool
    runs: 'vpxenc --help

      '
  - name: Test vpxdec tool
    runs: 'vpxdec --help

      '
