package:
  name: mujs
  version: 1.3.7
  epoch: 0
  description: Lightweight JavaScript interpreter
  copyright:
  - license: ISC
environment:
  contents:
    packages:
    - build-base
    - busybox
    - ca-certificates-bundle
    - curl
    - python3
    - readline-dev
    - wget
    - wolfi-base
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/ArtifexSoftware/mujs.git
    tag: ${{package.version}}
    expected-commit: 05cd646bad083ed45e9e1c9846ea671d461ced30
- uses: fetch
  with:
    uri: https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
    expected-sha256: 2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c
- uses: fetch
  with:
    uri: https://www.unicode.org/Public/17.0.0/ucd/SpecialCasing.txt
    expected-sha256: efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588
- runs: |
    # Copy fetched Unicode data files to build directory
    cp ${{targets.contextdir}}/UnicodeData.txt .
    cp ${{targets.contextdir}}/SpecialCasing.txt .
- uses: autoconf/make
  with:
    opts: 'prefix=/usr \

      CFLAGS="-fPIC" \

      release

      '
- runs: 'make prefix=/usr DESTDIR="${{targets.destdir}}" install-shared

    '
- uses: strip
subpackages:
- name: mujs-dev
  pipeline:
  - uses: split/dev
  dependencies:
    runtime:
    - mujs
  description: mujs development files
  test:
    pipeline:
    - uses: test/pkgconf
update:
  enabled: true
  release-monitor:
    identifier: 269367
test:
  pipeline:
  - uses: test/tw/ldd-check
  - name: Test mujs binary
    runs: 'mujs -v

      '
  - uses: test/pkgconf
