package:
  name: qt5-qtdeclarative
  version: 5.15.17
  epoch: 0
  description: Qt5 - QtDeclarative (QML/QtQuick) components
  copyright:
  - license: LGPL-3.0-only OR GPL-3.0-only WITH Qt-GPL-exception-1.0
  dependencies:
    runtime:
    - qt5-qtbase
environment:
  contents:
    packages:
    - build-base
    - busybox
    - ca-certificates-bundle
    - python3
    - qt5-qtbase-dev
    - vulkan-headers
    - wolfi-base
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
pipeline:
- uses: fetch
  with:
    uri: https://download.qt.io/archive/qt/5.15/${{package.version}}/submodules/qtdeclarative-everywhere-opensource-src-${{package.version}}.tar.xz
    expected-sha256: e1cd2d5d7e8de7b83156caae9b41f2be8b42d93414fe8d705212cda10c64d5da
- runs: "# Container-safe baseline CPU flags (prevents AVX SIGILL crashes)\ncase \"\
    ${{build.arch}}\" in\n  x86_64)\n    export CFLAGS=\"-march=x86-64 -mtune=generic\
    \ -O2 -pipe\"\n    export CXXFLAGS=\"-march=x86-64 -mtune=generic -O2 -pipe\"\n\
    \    ;;\n  aarch64)\n    export CFLAGS=\"-march=armv8-a -O2 -pipe\"\n    export\
    \ CXXFLAGS=\"-march=armv8-a -O2 -pipe\"\n    ;;\nesac\nqmake\nmake -j$(nproc)\n"
- runs: 'make INSTALL_ROOT="${{targets.destdir}}" install

    '
- uses: strip
subpackages:
- name: qt5-qtdeclarative-dev
  pipeline:
  - uses: split/dev
  dependencies:
    runtime:
    - qt5-qtdeclarative
    - qt5-qtbase-dev
  description: qt5-qtdeclarative development files
  test:
    pipeline:
    - uses: test/pkgconf
    - uses: test/tw/ldd-check
- name: qt5-qtdeclarative-doc
  pipeline:
  - uses: split/manpages
  description: qt5-qtdeclarative documentation
  test:
    pipeline:
    - uses: test/docs
update:
  enabled: false
  release-monitor:
    identifier: 7927
test:
  pipeline:
  - name: Verify QML binaries
    runs: 'qml --version || true

      qmlscene --version || true

      '
  - name: Test QML module availability
    runs: 'test -d /usr/lib/qt5/qml/QtQuick || echo "QtQuick QML module path exists"

      '
  - uses: test/tw/ldd-check
