package:
  name: qt5-qtbase
  version: 5.15.17
  epoch: 5
  description: Qt5 - QtBase components
  copyright:
  - license: LGPL-3.0-only OR GPL-3.0-only WITH Qt-GPL-exception-1.0
  dependencies:
    runtime:
    - libglvnd
  resources:
    cpu: 32
    memory: 16Gi
environment:
  contents:
    packages:
    - at-spi2-core-dev
    - bison
    - build-base
    - busybox
    - ca-certificates-bundle
    - cups-dev
    - dbus-dev
    - flex
    - fontconfig-dev
    - freetds-dev
    - freetype-dev
    - gawk
    - glib-dev
    - gperf
    - gtk-3-dev
    - hicolor-icon-theme
    - icu-dev
    - libice-dev
    - libinput-dev
    - libjpeg-turbo-dev
    - libpng-dev
    - libsm-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - libxrender-dev
    - libxslt-dev
    - libxv-dev
    - mariadb-connector-c-dev
    - mariadb-dev
    - mesa
    - mesa-dev
    - mesa-egl
    - mesa-glx
    - mtdev-dev
    - openssh-client
    - openssl-dev
    - pcre2-dev
    - perl
    - perl-dev
    - postgresql-16-dev
    - sqlite-dev
    - systemd-dev
    - unixodbc-dev
    - vulkan-headers
    - libxcb-dev
    - libxcb-glx
    - xcb-util-dev
    - xcb-util-image-dev
    - xcb-util-keysyms-dev
    - xcb-util-renderutil-dev
    - xcb-util-wm-dev
    - xdg-utils
    - zlib-dev
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
  environment:
    QT5_PREFIX: /usr/lib/qt5
    QT5_DATADIR: /usr/share/qt5
pipeline:
- uses: fetch
  with:
    expected-sha256: db1513cbb3f4a5bd2229f759c0839436f7fe681a800ff2bc34c4960b09e756ff
    uri: https://download.qt.io/archive/qt/5.15/${{package.version}}/submodules/qtbase-everywhere-opensource-src-${{package.version}}.tar.xz
- uses: patch
  with:
    patches: qt5-qtbase/qt5-base-cflags.patch qt5-qtbase/egl-x11.patch
- runs: "# Container-safe baseline CPU flags (prevents AVX SIGILL crashes)\ncase \"\
    ${{build.arch}}\" in\n  x86_64)\n    export CFLAGS=\"-march=x86-64 -mtune=generic\
    \ -O2\"\n    export CXXFLAGS=\"-march=x86-64 -mtune=generic -O2\"\n    ;;\n  aarch64)\n\
    \    export CFLAGS=\"-march=armv8-a -O2\"\n    export CXXFLAGS=\"-march=armv8-a\
    \ -O2\"\n    ;;\nesac\n\nsed -i -e \"s|-O3|$CXXFLAGS|\" \\\n  -e \"/^QMAKE_RPATH/s|\
    \ -Wl,-rpath,||g\" \\\n  -e \"/^QMAKE_LFLAGS\\s/s|+=|+= $LDFLAGS|g\" \\\n  mkspecs/common/*.conf\n\
    \n# Make configure think we are running in a git directory\n# This makes it symlink\
    \ the include files to the right directory\nmkdir -p .git\n\n# Use OpenGL ES2\
    \ on aarch64\nif [[ \"${{build.arch}}\" == \"aarch64\" ]]; then\n  _opengl=\"\
    -opengl es2\"\nelse\n  _opengl=\"-opengl desktop\"\nfi\n\n./configure \\\n  -confirm-license\
    \ \\\n  -opensource \\\n  -prefix /usr \\\n  -archdatadir \"$QT5_PREFIX\" \\\n\
    \  -bindir \"$QT5_PREFIX\"/bin \\\n  -datadir \"$QT5_DATADIR\" \\\n  -libdir /usr/lib\
    \ \\\n  -dbus-linked \\\n  -docdir /usr/share/doc/qt5 \\\n  -examplesdir /usr/share/doc/qt5/examples\
    \ \\\n  -glib \\\n  -headerdir /usr/include/qt5 \\\n  -icu \\\n  -importdir \"\
    $QT5_PREFIX\"/imports \\\n  -libexecdir \"$QT5_PREFIX\"/libexec \\\n  -no-rpath\
    \ \\\n  -no-separate-debug-info \\\n  -no-pch \\\n  -nomake examples \\\n  $_opengl\
    \ \\\n  -xcb \\\n  -xcb-xlib \\\n  -egl \\\n  -feature-xcb-glx-plugin \\\n  -openssl-linked\
    \ \\\n  -optimized-qmake \\\n  -plugin-sql-mysql \\\n  -plugin-sql-odbc \\\n \
    \ -plugin-sql-psql \\\n  -plugin-sql-sqlite \\\n  -plugin-sql-tds \\\n  -plugindir\
    \ \"$QT5_PREFIX\"/plugins \\\n  -system-libjpeg \\\n  -system-libpng \\\n  -system-pcre\
    \ \\\n  -system-sqlite \\\n  -system-zlib \\\n  -translationdir \"$QT5_DATADIR\"\
    /translations \\\n  -no-reduce-relocations \\\n  -no-sse3 \\\n  -no-ssse3 \\\n\
    \  -no-sse4.1 \\\n  -no-sse4.2 \\\n  -no-avx \\\n  -no-avx2 \\\n  -no-avx512\n\
    \n# significantly reduce debug symbol size\nCFLAGS=\"$CFLAGS -g1\" \\\nCXXFLAGS=\"\
    $CXXFLAGS -g1\" \\\nmake -j$(nproc)\n\nmake INSTALL_ROOT=\"${{targets.destdir}}\"\
    \ install\n\nmkdir -p ${{targets.destdir}}/usr/bin/\nfor i in ${{targets.destdir}}/\"\
    $QT5_PREFIX\"/bin/*; do\n  _name=${i##*/}\n  case $_name in\n    *.*) _dest=${{targets.destdir}}/usr/bin/${_name%.*}-qt5.${_name##*.};;\n\
    \    *) _dest=${{targets.destdir}}/usr/bin/${_name%.*}-qt5;;\n  esac\n  ln -sf\
    \ ../lib/qt5/bin/\"$_name\" \"$_dest\"\n  ln -sf ../lib/qt5/bin/\"$_name\" ${{targets.destdir}}/usr/bin/$_name\n\
    done\n\n# Drop QMAKE_PRL_BUILD_DIR because reference the build dir\nfind \"${{targets.destdir}}/usr/lib\"\
    \ -type f -name '*.prl' \\\n  -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \\\
    ;\n"
- uses: strip
subpackages:
- name: qt5-qtbase-dev
  pipeline:
  - uses: split/dev
  dependencies:
    runtime:
    - qt5-qtbase
    - qt5-qtbase-sqlite
    - qt5-qtbase-odbc
    - qt5-qtbase-postgresql
    - qt5-qtbase-mysql
    - qt5-qtbase-tds
    - qt5-qtbase-x11
    - dbus-dev
    - fontconfig-dev
    - freetype-dev
    - glib-dev
    - libice-dev
    - libpng-dev
    - libsm-dev
    - libx11-dev
    - libxext-dev
    - mesa-dev
    - openssl-dev
    - perl
    - sqlite-dev
    - zlib-dev
    - icu
  description: qt5-qtbase dev
  test:
    pipeline:
    - uses: test/pkgconf
    - uses: test/tw/ldd-check
- name: qt5-qtbase-doc
  pipeline:
  - uses: split/manpages
  description: qt5-qtbase manpages
  test:
    pipeline:
    - uses: test/docs
- name: qt5-qtbase-sqlite
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers

      mv ${{targets.destdir}}/usr/lib/qt5/plugins/sqldrivers/libqsqlite* ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers/

      '
  description: SQLite driver for Qt5's SQL classes
  test:
    pipeline:
    - uses: test/tw/ldd-check
- name: qt5-qtbase-odbc
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers

      mv ${{targets.destdir}}/usr/lib/qt5/plugins/sqldrivers/libqsqlodbc* ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers/

      '
  description: ODBC driver for Qt5's SQL classes
  test:
    pipeline:
    - uses: test/tw/ldd-check
- name: qt5-qtbase-postgresql
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers

      mv ${{targets.destdir}}/usr/lib/qt5/plugins/sqldrivers/libqsqlpsql* ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers/

      '
  description: PostgreSQL driver for Qt5's SQL classes
  test:
    pipeline:
    - uses: test/tw/ldd-check
- name: qt5-qtbase-mysql
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers

      mv ${{targets.destdir}}/usr/lib/qt5/plugins/sqldrivers/libqsqlmysql* ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers/

      '
  description: MySQL driver for Qt5's SQL classes
  test:
    pipeline:
    - uses: test/tw/ldd-check
- name: qt5-qtbase-tds
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers

      mv ${{targets.destdir}}/usr/lib/qt5/plugins/sqldrivers/libqsqltds* ${{targets.subpkgdir}}/usr/lib/qt5/plugins/sqldrivers/

      '
  description: TDS driver for Qt5's SQL classes
  test:
    pipeline:
    - uses: test/tw/ldd-check
- name: qt5-qtbase-x11
  pipeline:
  - runs: "mkdir -p ${{targets.subpkgdir}}/usr/lib/qt5/plugins\nmv ${{targets.destdir}}/usr/lib/libQt5EglFSDeviceIntegration.so.*\
      \ ${{targets.subpkgdir}}/usr/lib/\nmv ${{targets.destdir}}/usr/lib/libQt5Gui.so.*\
      \ ${{targets.subpkgdir}}/usr/lib/\nmv ${{targets.destdir}}/usr/lib/libQt5OpenGL.so.*\
      \ ${{targets.subpkgdir}}/usr/lib/\nmv ${{targets.destdir}}/usr/lib/libQt5PrintSupport.so.*\
      \ ${{targets.subpkgdir}}/usr/lib/\nmv ${{targets.destdir}}/usr/lib/libQt5Widgets.so.*\
      \ ${{targets.subpkgdir}}/usr/lib/\nmv ${{targets.destdir}}/usr/lib/libQt5XcbQpa.so.*\
      \ ${{targets.subpkgdir}}/usr/lib/\nmv ${{targets.destdir}}/usr/lib/qt5/plugins/egldeviceintegrations\
      \ ${{targets.subpkgdir}}/usr/lib/qt5/plugins/\nmv ${{targets.destdir}}/usr/lib/qt5/plugins/generic\
      \ ${{targets.subpkgdir}}/usr/lib/qt5/plugins/\nmv ${{targets.destdir}}/usr/lib/qt5/plugins/image*\
      \ ${{targets.subpkgdir}}/usr/lib/qt5/plugins/\nmv ${{targets.destdir}}/usr/lib/qt5/plugins/platform*\
      \ ${{targets.subpkgdir}}/usr/lib/qt5/plugins/\nmv ${{targets.destdir}}/usr/lib/qt5/plugins/printsupport*\
      \ ${{targets.subpkgdir}}/usr/lib/qt5/plugins/\nif [[ \"${{build.arch}}\" ==\
      \ \"x86_64\" ]]; then\n  mv ${{targets.destdir}}/usr/lib/qt5/plugins/xcbglintegrations\
      \ ${{targets.subpkgdir}}/usr/lib/qt5/plugins/\nfi\n"
  description: Qt5 GUI-related libraries
  test:
    pipeline:
    - uses: test/tw/ldd-check
update:
  enabled: true
  release-monitor:
    identifier: 320206
test:
  pipeline:
  - runs: 'moc --version

      moc-qt5 --version

      qdbuscpp2xml --help

      qdbuscpp2xml-qt5 --help

      qdbusxml2cpp --version

      qdbusxml2cpp-qt5 --version

      qlalr --help

      qlalr-qt5 --help

      qmake --version

      qmake-qt5 --version

      rcc --version

      rcc-qt5 --version

      uic --version

      uic-qt5 --version

      moc --help

      moc-qt5 --help

      qdbusxml2cpp --help

      qdbusxml2cpp-qt5 --help

      qlalr -v

      qlalr-qt5 -v

      qmake --help

      qmake-qt5 --help

      rcc --help

      rcc-qt5 --help

      uic --help

      uic-qt5 --help

      '
  - uses: test/tw/ldd-check
