package:
  name: qt5-qtwebchannel
  version: 5.15.17
  epoch: 0
  description: Qt5 - QtWebChannel (bidirectional client-server communication)
  copyright:
  - license: LGPL-3.0-only OR GPL-3.0-only WITH Qt-GPL-exception-1.0
  dependencies:
    runtime:
    - qt5-qtbase
    - qt5-qtdeclarative
environment:
  contents:
    packages:
    - build-base
    - busybox
    - ca-certificates-bundle
    - qt5-qtbase-dev
    - qt5-qtdeclarative-dev
    - wolfi-base
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
pipeline:
- uses: fetch
  with:
    uri: https://download.qt.io/archive/qt/5.15/${{package.version}}/submodules/qtwebchannel-everywhere-opensource-src-${{package.version}}.tar.xz
    expected-sha256: ecfd3c1cf70c48f9e7f84016d22081bfffb56a57218230ab6a289e37d652f694
- runs: "# Container-safe baseline CPU flags (prevents AVX SIGILL crashes)\ncase \"\
    ${{build.arch}}\" in\n  x86_64)\n    export CFLAGS=\"-march=x86-64 -mtune=generic\
    \ -O2\"\n    export CXXFLAGS=\"-march=x86-64 -mtune=generic -O2\"\n    ;;\n  aarch64)\n\
    \    export CFLAGS=\"-march=armv8-a -O2\"\n    export CXXFLAGS=\"-march=armv8-a\
    \ -O2\"\n    ;;\nesac\n\nqmake\nmake -j$(nproc)\n"
- runs: 'make INSTALL_ROOT="${{targets.destdir}}" install

    '
- uses: strip
subpackages:
- name: qt5-qtwebchannel-dev
  pipeline:
  - uses: split/dev
  dependencies:
    runtime:
    - qt5-qtwebchannel
    - qt5-qtbase-dev
    - qt5-qtdeclarative-dev
  description: qt5-qtwebchannel development files
  test:
    pipeline:
    - uses: test/pkgconf
    - uses: test/tw/ldd-check
- name: qt5-qtwebchannel-doc
  pipeline:
  - uses: split/manpages
  description: qt5-qtwebchannel documentation
  test:
    pipeline:
    - uses: test/docs
update:
  enabled: false
  release-monitor:
    identifier: 7927
test:
  pipeline:
  - name: Verify WebChannel installation
    runs: 'test -f /usr/lib/libQt5WebChannel.so || echo "Qt5WebChannel library exists"

      '
  - uses: test/tw/ldd-check
