package:
  name: stremio
  version: 4.4.169
  epoch: 0
  description: Modern media center for online video content
  copyright:
  - license: GPL-3.0-or-later
  dependencies:
    runtime:
    - font-noto
    - fontconfig
    - libdrm
    - libnspr
    - libnss
    - librsvg
    - mesa
    - mesa-gbm
    - nodejs
    - qt5-qtbase
    - qt5-qtdeclarative
    - qt5-qtquickcontrols
    - qt5-qtquickcontrols2
    - qt5-qtwebchannel
    - qt5-qtwebengine
environment:
  contents:
    packages:
    - build-base
    - busybox
    - ca-certificates-bundle
    - cmake
    - libnspr-dev
    - libnss-dev
    - librsvg
    - mpv-dev
    - nodejs
    - npm
    - openssl-dev
    - pkgconf
    - qt5-qtbase-dev
    - qt5-qtdeclarative-dev
    - qt5-qtquickcontrols-dev
    - qt5-qtquickcontrols2-dev
    - qt5-qtwebchannel-dev
    - qt5-qtwebengine-dev
    - rsvg-convert
    - wolfi-base
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/Stremio/stremio-shell
    tag: v${{package.version}}
    expected-commit: 0589927cb53bc68e09776ec94ce3860b64ca10a4
- uses: patch
  with:
    patches: stremio/001-release-makefile-fhs.patch
- uses: patch
  with:
    patches: stremio/002-cmake-add-singleapp.patch
- uses: patch
  with:
    patches: stremio/003-qtwebengine-correct.patch
- uses: patch
  with:
    patches: stremio/004-fhs-server-paths.patch
- uses: patch
  with:
    patches: stremio/005-process-environment-fix.patch
- uses: patch
  with:
    patches: stremio/006-cmake-remove-singleapp-dep.patch
- uses: patch
  with:
    patches: stremio/007-remove-qthelper-deprecated.patch
- uses: patch
  with:
    patches: stremio/008-disable-systemtray-wolfi.patch
- uses: patch
  with:
    patches: stremio/009-intelligent-gpu-detection.patch
- uses: patch
  with:
    patches: stremio/010-mpv-libmpv-software-rendering.patch
- name: Generate icons
  runs: "mkdir -p icons\ncd icons\nfor size in 16 22 24 32 64 128; do\n  rsvg-convert\
    \ ../images/stremio.svg -w $size -o smartcode-stremio_${size}.png\n  rsvg-convert\
    \ ../images/stremio_tray_white.svg -w $size -o smartcode-stremio-tray_${size}.png\n\
    done\n"
- name: Build with CMake
  runs: "export QT_SELECT=5\nexport QT_DEFAULT_MAJOR_VERSION=5\nexport CMAKE_PREFIX_PATH=/usr/lib64/cmake:/usr/lib/cmake:/usr\n\
    \nmkdir -p build\ncd build\ncmake -G\"Unix Makefiles\" \\\n  -DCMAKE_BUILD_TYPE=Release\
    \ \\\n  -DCMAKE_INSTALL_PREFIX=/usr \\\n  -DCMAKE_CXX_FLAGS=\"-fstack-protector-strong\
    \ -D_FORTIFY_SOURCE=2 -g\" \\\n  -DCMAKE_C_FLAGS=\"-fstack-protector-strong -D_FORTIFY_SOURCE=2\
    \ -g\" \\\n  ..\nmake -j$(nproc)\n"
- name: Install files
  runs: "# Install binary to libexec (not directly in PATH)\ninstall -Dm755 build/stremio\
    \ \"${{targets.destdir}}\"/usr/libexec/stremio/stremio\n\n# Install wrapper script\
    \ (from package subdirectory)\ninstall -Dm755 stremio/stremio-wrapper.sh \"${{targets.destdir}}\"\
    /usr/bin/stremio\n\n# Install desktop file\ninstall -Dm644 stremio.desktop \"\
    ${{targets.destdir}}\"/usr/share/applications/stremio.desktop\n\n# Install icons\
    \ (proper FreeDesktop hierarchy)\nfor size in 16 22 24 32 64 128; do\n  install\
    \ -Dm644 \"icons/smartcode-stremio_${size}.png\" \\\n    \"${{targets.destdir}}\"\
    /usr/share/icons/hicolor/${size}x${size}/apps/stremio.png\ndone\n\n# Install tray\
    \ icons\nmkdir -p \"${{targets.destdir}}\"/usr/share/stremio/icons/\nfor size\
    \ in 16 22 24 32 64 128; do\n  install -Dm644 \"icons/smartcode-stremio-tray_${size}.png\"\
    \ \\\n    \"${{targets.destdir}}\"/usr/share/stremio/icons/\ndone\n"
subpackages:
- name: stremio-doc
  description: Stremio documentation
  pipeline:
  - runs: 'mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/stremio

      install -Dm644 README.md "${{targets.subpkgdir}}"/usr/share/doc/stremio/

      install -Dm644 LICENSE.md "${{targets.subpkgdir}}"/usr/share/doc/stremio/

      '
  test:
    environment:
      contents:
        packages:
        - busybox
    pipeline:
    - uses: test/docs
update:
  enabled: true
  github:
    identifier: Stremio/stremio-shell
    strip-prefix: v
    use-tag: true
test:
  environment:
    contents:
      packages:
      - nodejs
      - qt5-qtbase
      - qt5-qtdeclarative
      - qt5-qtquickcontrols
      - qt5-qtquickcontrols2
      - qt5-qtwebengine
  pipeline:
  - name: Test binary exists and is executable
    runs: 'test -f /usr/bin/stremio

      test -x /usr/bin/stremio

      '
  - name: Test wrapper script
    runs: 'test -f /usr/libexec/stremio/stremio

      test -x /usr/libexec/stremio/stremio

      '
  - name: Test desktop file
    runs: 'test -f /usr/share/applications/stremio.desktop

      grep -q "Exec=stremio" /usr/share/applications/stremio.desktop

      '
  - name: Test icons installed
    runs: 'test -f /usr/share/icons/hicolor/16x16/apps/stremio.png

      test -f /usr/share/icons/hicolor/128x128/apps/stremio.png

      '
  - uses: test/tw/ldd-check
