package:
  name: zlib
  version: 1.3.1
  epoch: 52
  description: a library implementing the zlib compression algorithms
  copyright:
  - license: MPL-2.0 AND MIT
  dependencies:
    runtime:
    - merged-lib
    - wolfi-baselayout
environment:
  contents:
    packages:
    - autoconf
    - automake
    - build-base
    - busybox
    - ca-certificates-bundle
    - libtool
    - wolfi-baselayout
    keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    - https://packages.wolfi.dev/os
  environment:
    CFLAGS: ''
    CPPFLAGS: ''
    CXXFLAGS: ''
    LDFLAGS: ''
pipeline:
- uses: git-checkout
  with:
    expected-commit: 51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf
    repository: https://github.com/madler/zlib.git
    tag: v${{package.version}}
- runs: "./configure \\\n  --prefix=/usr \\\n  --libdir=/usr/lib \\\n  --shared\n"
- uses: autoconf/make
- runs: 'make install pkgconfigdir="/usr/lib/pkgconfig" DESTDIR="${{targets.destdir}}"

    '
- uses: strip
- runs: "cd contrib/minizip\nautoreconf -fiv\n./configure --prefix=/usr \\\n  --enable-static=no\n\
    make\nmake install DESTDIR=\"${{targets.destdir}}\"\n"
subpackages:
- name: zlib-static
  description: zlib static library
  pipeline:
  - uses: split/static
  dependencies:
    runtime:
    - merged-lib
    - wolfi-baselayout
- name: minizip
  description: a library for manipulation with files from .zip archives
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/lib

      mv ${{targets.destdir}}/usr/lib/libminizip.so.* ${{targets.subpkgdir}}/usr/lib/

      '
  test:
    pipeline:
    - uses: test/tw/ldd-check
  dependencies:
    runtime:
    - merged-lib
    - wolfi-baselayout
- name: minizip-dev
  description: minizip development headers
  pipeline:
  - runs: 'mkdir -p ${{targets.subpkgdir}}/usr/include

      mkdir -p ${{targets.subpkgdir}}/usr/lib/pkgconfig

      mkdir -p ${{targets.subpkgdir}}/usr/lib

      # Move headers

      mv ${{targets.destdir}}/usr/include/minizip ${{targets.subpkgdir}}/usr/include/

      # Move .so symlink (unversioned)

      mv ${{targets.destdir}}/usr/lib/libminizip.so ${{targets.subpkgdir}}/usr/lib/

      # Move pkgconfig

      mv ${{targets.destdir}}/usr/lib/pkgconfig/minizip.pc ${{targets.subpkgdir}}/usr/lib/pkgconfig/

      # Move .a files if they exist

      mv ${{targets.destdir}}/usr/lib/libminizip.a ${{targets.subpkgdir}}/usr/lib/
      || true

      '
  dependencies:
    runtime:
    - minizip
    - merged-lib
    - wolfi-baselayout
    - zlib-dev
  test:
    pipeline:
    - uses: test/pkgconf
    - uses: test/tw/ldd-check
- name: zlib-dev
  description: zlib development headers
  pipeline:
  - uses: split/dev
  dependencies:
    runtime:
    - merged-lib
    - wolfi-baselayout
    - zlib
  test:
    environment:
      contents:
        packages:
        - gcc
        - glibc-dev
        - wget
        - zlib-dev
    pipeline:
    - name: Compile and Test zlib
      runs: "# Download test file\nwget https://zlib.net/zpipe.c\n\n# Compile zpipe.c\n\
        gcc zpipe.c -I/usr/include -L/usr/lib -lz -o zpipe\n\nif [ $? -ne 0 ]; then\n\
        \  echo \"Compilation of zpipe failed\"\n  exit 1\nfi\n\n# Test compression\
        \ and decompression\ntext=\"Hello, zlib!\"\necho \"$text\" | ./zpipe > tmp.zlib\n\
        cat tmp.zlib | ./zpipe -d\n\nif [ $? -ne 0 ]; then\n  echo \"Test failed\"\
        \n  exit 1\nfi\n"
    - uses: test/pkgconf
    - uses: test/tw/ldd-check
- name: zlib-doc
  description: zlib docs
  pipeline:
  - uses: split/manpages
  test:
    pipeline:
    - uses: test/docs
  dependencies:
    runtime:
    - merged-lib
    - wolfi-baselayout
test:
  environment:
    contents:
      packages:
      - minizip
  pipeline:
  - uses: test/hardening-check
    with:
      package-match: zlib\|minizip
  - uses: test/tw/ldd-check
update:
  enabled: true
  github:
    identifier: madler/zlib
    strip-prefix: v
